### ISSUE TITLE
Does this really need a GPC support resource

### ISSUE THREAD

**Issue by martinthomson** [privacycg/gpc-spec#33]
The specification doesn't really make a very strong case for this feature and this is a specification that really needs to strongly justify every aspect of its design.  More mechanisms = larger attack surface.

**Comment by martinthomson** [comment]
[This resource](https://well-known.dev/?q=resource%3A%22gpc%22) lists a number of sites that produce the signal already.  I don't have an easy summary of how many of these say `gpc: true`.

**Comment by braedon** [comment]
You can use the [gpc_support](https://well-known.dev/?q=resource%3A%22gpc%22+gpc_support%3Atrue#results)  filter to find sites that say `gpc: true`.

[Here's the latest summary](https://twitter.com/gpcsup/status/1585632442634801153) from the Twitter bot. Note that its stats also filter out subdomains.

**Comment by pes10k** [comment]
Hi @martinthomson , this feature (the .well-known) is important for a couple of reasons:

1. Unlikely most other browser features, a site supporting GPC won't have any immediate, user (or browser) noticeable effects. This is very different than almost every other browser feature
2. the risk in terms of implementation complexity seems very very small
3. We expect that measuring site adoption will be important for a number of reasons (from regulators, academics / activists, auditors, etc) and so something like .well-known is needed (and .well-known seems simpler than other possibilities, like a fixed HTTP response header)

**Comment by martinthomson** [comment]
Hi @pes10k, of these, only the third strikes me as an actual reason.  It's not a terrible reason, but I'm concerned that the mechanism comes with downsides that are being disregarded.

What I really want to hear is that there is some legally-relevant reason for making a commitment, and whether this sort of resource would be consider adequate toward that end (as in non-repudiable if necessary, etc...).  A better outcome - at least from the legal effect of the system - might be to have no need for any such commitment.

I'm less convinced by the need to monitor for compliance.  Many sites have privacy policies that could adopt common language about compliance with GPC.  Given the need to understand the complexities of how data is handled by sites and their partners and subsidiaries, I see no significant advantage to having a special signal for this purpose.

As for this being cheap, I think that you underestimate the costs involved.  Though it seems simple, I don't think that it really is that easy.  Because there is no immediate effect from compliance, there is no reason for the resource to be actively validated.  And no matter how small a resource is, correctly serving it requires a non-trivial work in most organizations.

Overall, my view is that a smaller target is better.  That means cutting back on anything that is not very strongly motivated and this is the most complicated piece of the specification.  Well, outside of the essential part where a technical mechanism engages with any number of legal/regulatory mechanisms.

**Comment by SebastianZimmeck** [comment]
> Unlikely most other browser features, a site supporting GPC won't have any immediate, user (or browser) noticeable effects. This is very different than almost every other browser feature

In my view this is an important point. We did GPC usability studies (to appear in PETS next year), and some of the feedback we received from people was that they were unsure whether turning on GPC actually did anything. If there is at least a declaration on a site that it respects GPC, it could be picked up in a browser or other user agent and trigger a UI event.

Also, there is evidence that some operators find it useful: [6,093 sites](https://well-known.dev/?q=resource%3A%22gpc%22#results) sites use the resource; [5,869 sites](https://well-known.dev/?q=resource%3A%22gpc%22+gpc_support%3Atrue#results) set it to `true`. Other operators may decide to not use it. That is OK. It is voluntary (personally, I would actually favor the resource to be mandatory).

> What I really want to hear is that there is some legally-relevant reason for making a commitment ...

Implementing the resource and setting it to `true` is a declaration that a site respects GPC. That makes life for regulators a bit easier. If a site does not respect GPC contrary to its declaration, there is a clear compliance issue.

> Many sites have privacy policies that could adopt common language about compliance with GPC. 

That is true. Respecting GPC could also be written in the privacy policy of a site. But since there is no common language, it would be much harder to automate and scale GPC compliance (declaration) analysis.

**Comment by darobin** [comment]
We've had this debate multiple times. The one and only value that I see is that regulators can use it as a deceptive declaration if someone has it set to `true` but does not abide. None of the other reasons stick (eg. browsers are never going to surface that in the UI.)

As I've said before, I don't think that it accomplishes anything that a standard statement in the PP wouldn't perform almost equally well, it adds complexity and the odds that things will go out of sync (no legal team can manage a `.well-know` which means that they'll need a process to update it when they change anything GPC-related, which they won't), and it keeps purely client-side implementations from existing (and those are the norm in CMP-land).

I certainly could live without it; it could also be put in a separate spec to live on its own merits.

**Comment by SebastianZimmeck** [comment]
@braedon, FYI, we plan to discuss this issue in the February 23 PrivacyCG call.

**Comment by braedon** [comment]
@SebastianZimmeck Thanks, is that going to be in the Noon or 7pm EST timeslot?

**Comment by SebastianZimmeck** [comment]
@braedon, this would be at noon EST.

**Comment by braedon** [comment]
I'm unlikely to make the call unfortunately - that's 1am for me. A few notes:

For tracking adoption, the well-known resource is MASSIVELY superior to a statement in the PP, even standardized. I originally threw together gpcsup.com in a few hours - it'd simply not have been feasible to build if I had to find and parse privacy policies. This use case isn't critical, but I think it has value.

Similarly, surfacing support status to users in the browser would be reliant on the resource to be practical. I disagree with Robin here - IMO once there's decent adoption browsers should surface it so users can make informed browsing decisions (and if they don't, it should be feasible for extensions to).

I'm also not sure why sites would need to update it whenever they change "anything GPC-related" - or rather I'm not sure what changes would require an update to the resource and be frequent enough to cause an issue? I'd hope sites aren't changing whether they support GPC more than once or twice on average, and as I understand it, the `lastUpdate` field should at max only need to be updated if/when the spec is updated?

Overall, I don't have particularly strong feelings, but would lean to keep it since it's already there, and IMO it's useful even if it's not essential.

**Comment by braedon** [comment]
(If anyone has any questions on adoption I'm seeing, or anything like that, let me know.)

**Comment by j-br0** [comment]
So we did discuss this issue at length on the PrivacyCG call today (notes [here](https://docs.google.com/document/d/1DZEhS1UHJ1PKxt5ZwKmn5LZ4bo10UFyNXeLp2dUuzRM/edit#heading=h.dm21kstbhcht)). In general, the discussion tracked the commentary in the thread. The biggest point of agreement was that maintenance of a well-known should not be mandatory largely because of the impact on small publishers (it is currently [optional](https://privacycg.github.io/gpc-spec/#gpc-support-resource) in the spec). Otherwise, while there was mild disagreement over the value of the signal, no one seemed to think that the optional resource should be a barrier to going forward with this process. For this reason, the editors indicated on the call that we are likely to close the issue next week --- however, if folks who were not on the call feel more strongly and/or believe that inclusion of an optional well-known in the spec would be a barrier to moving forward, please speak up and we can continue to discuss.

Relatedly, we also discussed whether the optional well-known resource should be revised to provide more detailed information about site compliance. Right now the [spec](https://privacycg.github.io/gpc-spec/#gpc-support-representation) only includes a gpc field which returns as true or false, and a lastUpdate field to indicate the time the statement of support was made. Seperately, @pes10k has filed PR #48 to propose to clarify that the resource should indicate whether a site respects GPC with respect to _the specific user_ accessing the resource. We also briefly discussed whether a static resource could provide more specificity as to in which jurisdictions GPC is honored, and whether the lastUpdated field still provides any value. Assuming we move forward with inclusion of the optional resource, we intend to continue to discuss those options.

**Comment by AramZS** [comment]
If there are further issues please submit as a separate issue.
